name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Ch-Kumar-Kartik

          template: classic
          base: activity, community, repositories

          # ðŸ”¥ WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, editors, projects, os
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_timezone: Asia/Kolkata

          # Output
          output_action: commit
          output_path: metrics.svg
