name: Waka Readme

on:
  schedule:
    - cron: '0 23 * * *' # runs daily at 23:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: false
          LANG_COUNT: 5
          BLOCKS: ░▒▓█
          COMMIT_MESSAGE: "Updated WakaTime stats"
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
