# name: Waka Readme

# on:
#   schedule:
#     - cron: '0 23 * * *' # runs daily at 23:00 UTC
#   workflow_dispatch:

# jobs:
#   update-readme:
#     name: Update README with WakaTime stats
#     runs-on: ubuntu-latest
#     steps:
#       - uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           TIME_RANGE: last_7_days
#           SHOW_TIME: true
#           SHOW_TOTAL: false
#           SHOW_MASKED_TIME: false
#           LANG_COUNT: 5
#           BLOCKS: ░▒▓█
#           COMMIT_MESSAGE: "Updated WakaTime stats"
#           SHOW_LINES_OF_CODE: true
#           SHOW_PROFILE_VIEWS: "False"
#           SHOW_COMMIT: "True"
#           SHOW_LANGUAGE: "True"
#           SHOW_OS: true
#           SHOW_PROJECTS: true
#           SHOW_TIMEZONE: true
#           SHOW_EDITORS: true
#           SHOW_SHORT_INFO: "False"
#           SHOW_LOC_CHART: "False"
#           LOCALE: "en"
name: Waka Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Ch-Kumar-Kartik/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_CODE_TIME: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_PROJECTS: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_COMMIT: "True"
          LOCALE: "en"
